n=int(input("So tien ban dau: "))
k=int(input("So thang gui: "))
T=float(input('Lai suat/ thang: '))
print("Voi so tien ban dau "+str(int(n))+", sau "+str(int(k))+" thang gui, lai suat "+str(float(T))+"/ thang")
print("Thi so tien nhan duoc cuoi ky la:",n*(1+k*T))